---

- name: Playbook_1_Lesson_3  
  hosts: web
  become: yes
   
  tasks:
  #установка httpd (Apache)
  - name: Installing httpd
    action: yum name={{ service_apache }} state=present
  #создание файла index.html и копирование в нужную папка
  - name: Copy index.html to directory
    become: yes
    copy:
      dest: "{{ my_path }}"
      content: "{{ message_for_web_page }}"

    #Применение Handler в случае изменения содержания страницы
    notify: Restart HTTPD
    
  #запуск сервера при каждом старте и статус его всегда enabled
  - name: Start httpd and enable it on every boot
    service:
     name: "{{ service_apache }}"
     enabled: yes
     state: started
  #открытие портов для запросов на сервер
  - name: Allow HTTP Service in Linux Firewall
    firewalld:
      port: "{{ item }}/tcp"
      #постоянно делать данное правило, даже при перезагрузке
      permanent: yes
      state: enabled
    #обходим циклом по всем портам, заданным в group_vars\web
    loop: "{{ ports_for_apache }}"
    
  #проверка статуса службы сервиса httpd
  - name: See httpd FATCS
    service_facts:
    register: services_state
  - debug:
      #var=services_state.ansible_facts.services["httpd.service"].state
      msg: "{{ ansible_facts.services['httpd.service'].state }}"
  - name: Verify apache is running
    assert:
      that:
        - "'{{ ansible_facts.services['httpd.service'].state }}' == 'running'"
      fail_msg: "Apache is down for some reason!"
      success_msg: "Apache is running!! It is ok!"

  handlers:
    - name: Restart HTTPD
      service:
        name: httpd
        state: restarted

...