---

- name: Playbook_1_Lesson_2  
  hosts: nodes
  become: yes
  #Шифрованный файл с паролями для всех трех пользователей:
  vars_files:
    - userpass1.yaml
  tasks:

  #Создание пользователя Alice
    - name: Create user account Alice
      user:
        name: "Alice"
        home: /home/Alice
        state: present
        shell: /bin/bash
        password: "{{ pwhash1 | password_hash('sha512') }}"
        comment: "alice@example.com"
        update_password: on_create

  #Создание пользователя Bob
    - name: Create user account Bob
      user:
        name: "Bob"
        home: /home/Bob
        state: present
        shell: /bin/bash
        password: "{{ pwhash2 | password_hash('sha512') }}"
        comment: "bob@example.com"
        update_password: on_create


  #Создание пользователя Carol
    - name: Create user account Carol
      user:
        name: "Carol"
        home: /home/Carol
        state: present
        shell: /bin/bash
        password: "{{ pwhash3 | password_hash('sha512') }}"
        comment: "carol@exapmle.com"
        update_password: on_create

...